# Generated by Django 5.2.6 on 2025-09-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Insurance Agency', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, help_text="Optional: Upload your agency's logo.", null=True, upload_to='agency_logos/')),
            ],
            options={
                'verbose_name_plural': 'Agency Information',
            },
        ),
    ]
