# Generated by Django 5.2.6 on 2025-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text="Customer's primary email.", max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], default='prospect', max_length=10)),
                ('source', models.CharField(blank=True, choices=[('walk_in', 'Walk-in'), ('transfer', 'Transfer'), ('pending', 'Pending'), ('referral', 'Referral'), ('web', 'Web'), ('other', 'Other')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal sticky note for the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
