name: CI

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: "pip-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: |
          pip-${{ runner.os }}-py${{ matrix.python-version }}-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install Django==5.2.6 flake8; fi

    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        # run flake8 on the repository, ignore migrations and env
        flake8 --exclude=env,webapplicationtutorial/*/migrations --max-line-length=100

    - name: Run migrations & tests
      env:
        DJANGO_SETTINGS_MODULE: webapplicationtutorial.settings
      run: |
        python webapplicationtutorial/manage.py migrate --noinput
        python webapplicationtutorial/manage.py test -v 2
